services: # each service is a container (postgres)
  postgres:
    image: postgres:16-alpine
    container_name: stockintel-postgres
    environment: #creates user based on these vars on first boot
      POSTGRES_USER: stockintel
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: stockintel
    ports:
      - "5432:5432"
    volumes: #saves the database from deletion when container is deleted
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stockintel -d stockintel"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: stockintel-api
    depends_on:
      postgres:
        condition: service_healthy # API waits for postgres to be healthy before starting
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=stockintel;Username=stockintel;Password=localdev" #connection string
      Jwt__Issuer: stockintel-api
      Jwt__Audience: stockintel-clients
      Jwt__SigningKey: "this-is-a-development-only-signing-key-at-least-32-chars"
      Jwt__ExpirationMinutes: "60"
      Edgar__UserAgent: "StockIntel/0.2 (diego.a.gomez.ruiz@example.com)"
      Edgar__RequestsPerSecond: "5"
    ports:
      - "8080:8080"

volumes:
  postgres_data:

# double underscore is the convention for nested config keys. ConnectionStrings__Postgres -> turns into ConnectionStrings:Postgres internally