// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockIntel.Infrastructure.Persistence;

#nullable disable

namespace StockIntel.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockIntel.Domain.Filings.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cik")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cik");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_company_name");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.CompanyTicker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("ticker");

                    b.HasKey("Id")
                        .HasName("pk_company_ticker");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_ticker_company_id");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("ix_company_ticker_ticker");

                    b.ToTable("company_ticker", (string)null);
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.InsiderFiling", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accession_number");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateOnly>("FilingDate")
                        .HasColumnType("date")
                        .HasColumnName("filing_date");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("InsiderCik")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("insider_cik");

                    b.Property<string>("InsiderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("insider_name");

                    b.Property<bool>("IsDirector")
                        .HasColumnType("boolean")
                        .HasColumnName("is_director");

                    b.Property<bool>("IsOfficer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_officer");

                    b.Property<bool>("IsTenPercentOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ten_percent_owner");

                    b.Property<string>("OfficerTitle")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("officer_title");

                    b.HasKey("Id")
                        .HasName("pk_insider_filing");

                    b.HasIndex("AccessionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_insider_filing_accession_number");

                    b.HasIndex("CompanyId", "FilingDate")
                        .HasDatabaseName("ix_insider_filing_company_id_filing_date");

                    b.ToTable("insider_filing", (string)null);
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.InsiderTransactions", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("code");

                    b.Property<Guid>("FilingId")
                        .HasColumnType("uuid")
                        .HasColumnName("filing_id");

                    b.Property<bool>("IsAcquisition")
                        .HasColumnType("boolean")
                        .HasColumnName("is_acquisition");

                    b.Property<bool>("IsDirectOwnership")
                        .HasColumnType("boolean")
                        .HasColumnName("is_direct_ownership");

                    b.Property<decimal?>("PricePerShare")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_per_share");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shares");

                    b.Property<decimal?>("SharesOwnedAfter")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("shares_owned_after");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id")
                        .HasName("pk_insider_transactions");

                    b.HasIndex("FilingId")
                        .HasDatabaseName("ix_insider_transactions_filing_id");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_insider_transactions_transaction_date");

                    b.ToTable("insider_transactions", (string)null);
                });

            modelBuilder.Entity("StockIntel.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StockIntel.Domain.Users.Watchlists.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlists");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_watchlists_user_id");

                    b.ToTable("watchlists", (string)null);
                });

            modelBuilder.Entity("StockIntel.Domain.Users.Watchlists.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("ticker");

                    b.Property<Guid>("WatchlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("watchlist_id");

                    b.HasKey("Id")
                        .HasName("pk_watchlist_items");

                    b.HasIndex("WatchlistId")
                        .HasDatabaseName("ix_watchlist_items_watchlist_id");

                    b.HasIndex("WatchlistId", "Ticker")
                        .IsUnique()
                        .HasDatabaseName("ix_watchlist_items_watchlist_id_ticker");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.CompanyTicker", b =>
                {
                    b.HasOne("StockIntel.Domain.Filings.Company", null)
                        .WithMany("Tickers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_ticker_company_company_id");
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.InsiderFiling", b =>
                {
                    b.HasOne("StockIntel.Domain.Filings.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_insider_filing_company_company_id");
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.InsiderTransactions", b =>
                {
                    b.HasOne("StockIntel.Domain.Filings.InsiderFiling", null)
                        .WithMany("Transactions")
                        .HasForeignKey("FilingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_insider_transactions_insider_filing_filing_id");
                });

            modelBuilder.Entity("StockIntel.Domain.Users.Watchlists.WatchlistItem", b =>
                {
                    b.HasOne("StockIntel.Domain.Users.Watchlists.Watchlist", null)
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchlist_items_watchlists_watchlist_id");
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.Company", b =>
                {
                    b.Navigation("Tickers");
                });

            modelBuilder.Entity("StockIntel.Domain.Filings.InsiderFiling", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockIntel.Domain.Users.Watchlists.Watchlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
